"""Real-data ingestion stub for PALLET-VISION.

The synthetic sample bank in `sample_images/` is generated by `generate.py` so
the demo runs offline. To plug in **real** drone / warehouse / loading-dock
imagery, point the app at a folder of JPEG/PNG files via:

    export REAL_DATA_PATH=/abs/path/to/folder/of/photos

The app will list everything in that folder and run the same multimodal
quantification pipeline against the real frames.

Cited datasets (LOGCOM portal):

  1. HIT-UAV — High-altitude Infrared Thermal UAV dataset
     URL:  https://github.com/suojiashun/HIT-UAV-Infrared-Thermal-Dataset
     Use:  drone-overhead frames; vehicles + people; 2898 IR images.
     Plug-in: download repo, set REAL_DATA_PATH=<repo>/normal_xml/JPEGImages

  2. Moving objects in construction sites (10,013 images)
     Public construction-site object detection corpus; pallets, equipment,
     personnel — closest open-source proxy for warehouse / dock palletization.
     Plug-in: download images, set REAL_DATA_PATH=<dir>

Required file shape: any JPEG or PNG; resolution is normalized to <=1024 px on
the long edge before the vision call. No labels / annotations are required at
inference time — the multimodal model produces quantification JSON directly.
"""
from __future__ import annotations

import os
from pathlib import Path


def list_real_samples(root: str | None = None) -> list[Path]:
    """Return absolute paths to every JPEG/PNG in REAL_DATA_PATH.

    If REAL_DATA_PATH is unset, returns []. Caller falls back to synthetic
    samples.
    """
    root = root or os.getenv("REAL_DATA_PATH")
    if not root:
        return []
    p = Path(root).expanduser().resolve()
    if not p.exists() or not p.is_dir():
        raise NotImplementedError(
            f"REAL_DATA_PATH={p} does not exist or is not a directory. "
            "See module docstring for download URLs."
        )
    out: list[Path] = []
    for ext in ("*.jpg", "*.jpeg", "*.JPG", "*.JPEG", "*.png", "*.PNG"):
        out.extend(sorted(p.glob(ext)))
    return out


if __name__ == "__main__":
    found = list_real_samples()
    if not found:
        print("REAL_DATA_PATH not set; using synthetic sample bank.")
    else:
        print(f"Found {len(found)} real images at {os.getenv('REAL_DATA_PATH')}:")
        for f in found[:10]:
            print(f"  {f.name}")
