"""Real-data ingestion stub for EMBODIED.

To plug in real Xperience-10M data, implement load_real() to read from a
curated subset of Xperience-10M and emit the same shape as data/generate.py
produces.

Source: Xperience-10M — large-scale egocentric multimodal dataset of human
experience for embodied AI / robot learning / world models.

Required fields per scenario (matches data/scenarios.json shape):
  - id:                  str    e.g. "x10m_breach_007"
  - title:               str    short scenario title
  - pov:                 str    1-3 sentence egocentric setup
  - scene_kind:          str    one of {doorway, checkpoint, casualty,
                                vehicle_interior, hallway, perimeter_night,
                                ied, civilian} OR a new key + matching draw fn
  - doctrine_reference:  str    MCWP / MCRP / TM citation Marines will recognize
  - correct_actions:     list[str]   doctrinal canonical answers
  - common_failures:     list[str]   anti-patterns we want the LLM to flag

Required per scenario, also:
  - data/frames/<id>.png         egocentric still extracted from the X10M clip

Then point src/app.py at it via env: REAL_DATA_PATH=/path/to/x10m_subset/
"""
from __future__ import annotations

import os
from pathlib import Path


def load_real() -> list[dict]:
    """Load real Xperience-10M scenarios + frames.

    Expected directory layout under REAL_DATA_PATH:
        REAL_DATA_PATH/
          scenarios.json       (same schema as data/scenarios.json)
          frames/<id>.png      (one per scenario)
    """
    path = os.getenv("REAL_DATA_PATH")
    if not path:
        raise NotImplementedError(
            "REAL_DATA_PATH not set. See docstring for required schema. "
            "Until configured, src/app.py reads data/scenarios.json + data/frames/ "
            "(synthetic procedural scenes generated by data/generate.py)."
        )
    root = Path(path)
    import json
    scenarios = json.loads((root / "scenarios.json").read_text())
    # spot-check that every frame exists
    missing = [s["id"] for s in scenarios
               if not (root / "frames" / f"{s['id']}.png").exists()]
    if missing:
        raise FileNotFoundError(f"Missing frames for scenario IDs: {missing}")
    return scenarios
