"""Real-data ingestion stub for REDLINE.

To plug REDLINE into a real document corpus, implement load_real() to
emit the same shape as data/generate.py's `list_sample_docs()` produces:

  [{"doc_id": "<id>", "title": "<title>",
    "path": "<rel-path>", "text": "<full text>"}, ...]

Real-data sources (any of these can plug in unchanged because the marking
logic is paragraph-text-based):

  - SharePoint export of a III MEF / LOGCOM working drafts library
  - Records-management corpus dumped from an EDMS (e.g. OpenText, Documentum)
  - DoDM 5200.01 reg corpus (for grounding) — e.g. dod.mil/dtic dumps
  - A directory of .docx files exported from Word
    (use python-docx: `from docx import Document; Document(p).paragraphs`)
  - A folder of .pdf files (use pdfminer.six or pypdfium2)

Set REAL_DATA_PATH=/path/to/dir or REAL_DATA_PATH=/path/to/manifest.json,
then call load_real(). The Streamlit UI will pick documents up
automatically because it reads from `cached_briefs.json` regenerated by
running `python data/generate.py` after load_real() drops new sample_docs.
"""
from __future__ import annotations

import json
import os
from pathlib import Path


def load_real() -> list[dict]:
    path = os.getenv("REAL_DATA_PATH")
    if not path:
        raise NotImplementedError(
            "REAL_DATA_PATH not set. Point at a directory of .txt / .docx / "
            ".pdf files (or a manifest.json) and re-run "
            "`python data/generate.py` to regenerate cached briefs."
        )
    p = Path(path)
    docs: list[dict] = []
    if p.is_file() and p.suffix == ".json":
        manifest = json.loads(p.read_text())
        for entry in manifest:
            doc_path = Path(entry["path"])
            docs.append({
                "doc_id": entry.get("doc_id", doc_path.stem),
                "title": entry.get("title", doc_path.stem),
                "path": str(doc_path),
                "text": doc_path.read_text(),
            })
    elif p.is_dir():
        for f in sorted(p.glob("*.txt")):
            docs.append({
                "doc_id": f.stem,
                "title": f.stem.replace("_", " ").upper(),
                "path": str(f),
                "text": f.read_text(),
            })
    else:
        raise FileNotFoundError(f"REAL_DATA_PATH={path} is neither file nor dir")
    return docs


if __name__ == "__main__":
    docs = load_real()
    print(f"Loaded {len(docs)} real documents")
    for d in docs:
        print(f"  {d['doc_id']}  ({len(d['text'])} chars)")
