"""Real-data ingestion stub for GUARDRAIL.

GUARDRAIL is a 4-layer governance workspace. Each layer has its own real-data
hook described below. None are wired by default — this stub documents the
swap recipe for the demo.

1. CUI corpus (REDLINE-style)
   Source: SharePoint export of a III MEF / LOGCOM working drafts library, or
           a directory of .docx / .pdf / .txt files exported from Word.
   Set REAL_CUI_DIR=/path/to/dir → load_real_docs() reads it and the Streamlit
   app reads from per_doc_markings.json regenerated by re-running
   `python data/generate.py`.

2. DTS-shape voucher records
   Source: TRAVEL-MGT export of synthetic / scrubbed DTS voucher records.
   Required cols: traveler_edipi, voucher_id, lines (list of {date, type,
   amount, location}), total, status.
   Set REAL_DTS_PATH=/path/to/vouchers.csv.

3. LMS-shape course materials
   Source: MarineNet / Moodle export — courses + transcripts.
   Required cols: course_id, title, body, classification, min_role.
   Set REAL_LMS_PATH=/path/to/courses.jsonl.

4. Browser intercept events
   Source: real browser SIEM (Splunk / Sentinel) export of intercepted
   browser-AI activity. Required fields match the synthetic shape in
   data/browser_events.jsonl exactly:
     event_id, timestamp_utc, client_ip, internal_app, endpoint, method,
     data_class, signals.{user_agent, ai_headers_present, dom_markers,
     navigator_webdriver, mouse_movement_entropy, screenshot_api_calls_30s}.
   Set REAL_BROWSER_EVENTS=/path/to/events.jsonl.

5. Role / permission tree (ABAC)
   Source: Keycloak realm export (users + roles + composite role mappings).
   Required cols: persona_id, name, rank, billet, clearance, abac.
   Set REAL_KEYCLOAK_REALM=/path/to/realm-export.json.
"""
from __future__ import annotations

import json
import os
from pathlib import Path


def load_real_docs() -> list[dict]:
    path = os.getenv("REAL_CUI_DIR")
    if not path:
        raise NotImplementedError(
            "REAL_CUI_DIR not set. Point at a directory of .txt / .docx / .pdf files "
            "and re-run `python data/generate.py` to regenerate marking caches."
        )
    p = Path(path)
    out: list[dict] = []
    if p.is_dir():
        for f in sorted(p.glob("*.txt")):
            out.append({
                "doc_id": f.stem,
                "title": f.stem.replace("_", " ").upper(),
                "path": str(f),
                "text": f.read_text(),
            })
    return out


def load_real_browser_events() -> list[dict]:
    path = os.getenv("REAL_BROWSER_EVENTS")
    if not path:
        raise NotImplementedError(
            "REAL_BROWSER_EVENTS not set. Point at a JSONL with the same shape "
            "as data/browser_events.jsonl (real Splunk / Sentinel export OK)."
        )
    out: list[dict] = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            out.append(json.loads(line))
    return out


def load_real_keycloak_realm() -> list[dict]:
    path = os.getenv("REAL_KEYCLOAK_REALM")
    if not path:
        raise NotImplementedError(
            "REAL_KEYCLOAK_REALM not set. Point at a Keycloak realm-export JSON. "
            "Walker maps realm.users[*].attributes → persona.abac fields."
        )
    raw = json.loads(Path(path).read_text())
    personas: list[dict] = []
    for u in raw.get("users", []):
        attrs = u.get("attributes", {}) or {}
        personas.append({
            "id": u["username"],
            "name": u.get("firstName", u["username"]),
            "rank": (attrs.get("rank") or [""])[0],
            "billet": (attrs.get("billet") or [""])[0],
            "duty_org": (attrs.get("duty_org") or [""])[0],
            "clearance": (attrs.get("clearance") or ["UNCLASS"])[0],
            "icon": (attrs.get("icon") or ["USR"])[0],
            "color": (attrs.get("color") or ["#7E7E7E"])[0],
            "abac": {
                "max_class": (attrs.get("max_class") or ["UNCLASS"])[0],
                "unit_scope": attrs.get("unit_scope", []),
                "roles": [r["name"] for r in u.get("realmRoles", [])],
                "need_to_know": attrs.get("need_to_know", []),
                "is_contractor": (attrs.get("is_contractor") or ["false"])[0] == "true",
                "foreign_national": (attrs.get("foreign_national") or ["false"])[0] == "true",
                "caveats_held": attrs.get("caveats_held", []),
            },
        })
    return personas


if __name__ == "__main__":
    for fn in (load_real_docs, load_real_browser_events, load_real_keycloak_realm):
        try:
            data = fn()
            print(f"{fn.__name__}: loaded {len(data)} records")
        except NotImplementedError as e:
            print(f"{fn.__name__}: stub — {e}")
